<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="3" ignored="3" total="8" passed="1" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[contact link clicked]]>
    </line>
    <line>
      <![CDATA[contact link clicked]]>
    </line>
    <line>
      <![CDATA[contact link clicked]]>
    </line>
    <line>
      <![CDATA[contact link clicked]]>
    </line>
  </reporter-output>
  <suite started-at="2023-09-21T11:57:11 IST" name="Default suite" finished-at="2023-09-21T11:57:34 IST" duration-ms="23280">
    <groups>
      <group name="RegressionSuite">
        <method signature="CreateContactTest.verifyUsercreateContactTest()[pri:0, instance:VTiger.CreateContactTest.CreateContactTest@1033576a]" name="verifyUsercreateContactTest" class="VTiger.CreateContactTest.CreateContactTest"/>
      </group> <!-- RegressionSuite -->
      <group name="smokesuite">
        <method signature="CreateContactTest.verifyUsercreateContactTest()[pri:0, instance:VTiger.CreateContactTest.CreateContactTest@1033576a]" name="verifyUsercreateContactTest" class="VTiger.CreateContactTest.CreateContactTest"/>
      </group> <!-- smokesuite -->
    </groups>
    <test started-at="2023-09-21T11:57:11 IST" name="Default test" finished-at="2023-09-21T11:57:34 IST" duration-ms="23280">
      <class name="VTiger.CreateContactTest.CreateContactTest">
        <test-method is-config="true" signature="bsConfig()[pri:0, instance:VTiger.CreateContactTest.CreateContactTest@1033576a]" started-at="2023-09-21T11:57:11 IST" name="bsConfig" finished-at="2023-09-21T11:57:11 IST" duration-ms="9" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bsConfig -->
        <test-method is-config="true" signature="bcConfig()[pri:0, instance:VTiger.CreateContactTest.CreateContactTest@1033576a]" started-at="2023-09-21T11:57:11 IST" name="bcConfig" finished-at="2023-09-21T11:57:14 IST" duration-ms="2405" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bcConfig -->
        <test-method is-config="true" signature="bmConfig()[pri:0, instance:VTiger.CreateContactTest.CreateContactTest@1033576a]" started-at="2023-09-21T11:57:14 IST" name="bmConfig" finished-at="2023-09-21T11:57:15 IST" duration-ms="1428" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bmConfig -->
        <test-method signature="create()[pri:0, instance:VTiger.CreateContactTest.CreateContactTest@1033576a]" started-at="2023-09-21T11:57:15 IST" name="create" finished-at="2023-09-21T11:57:15 IST" duration-ms="11" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create -->
        <test-method is-config="true" signature="amConfig()[pri:0, instance:VTiger.CreateContactTest.CreateContactTest@1033576a]" started-at="2023-09-21T11:57:15 IST" name="amConfig" finished-at="2023-09-21T11:57:17 IST" duration-ms="1765" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- amConfig -->
        <test-method is-config="true" signature="bmConfig()[pri:0, instance:VTiger.CreateContactTest.CreateContactTest@1033576a]" started-at="2023-09-21T11:57:17 IST" name="bmConfig" finished-at="2023-09-21T11:57:18 IST" duration-ms="1197" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bmConfig -->
        <test-method retried="true" signature="verifyUsercreateContactTest()[pri:0, instance:VTiger.CreateContactTest.CreateContactTest@1033576a]" started-at="2023-09-21T11:57:18 IST" name="verifyUsercreateContactTest" finished-at="2023-09-21T11:57:21 IST" duration-ms="2504" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at VTiger.CreateContactTest.CreateContactTest.verifyUsercreateContactTest(CreateContactTest.java:40)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[contact link clicked]]>
            </line>
          </reporter-output>
        </test-method> <!-- verifyUsercreateContactTest -->
        <test-method is-config="true" signature="amConfig()[pri:0, instance:VTiger.CreateContactTest.CreateContactTest@1033576a]" started-at="2023-09-21T11:57:21 IST" name="amConfig" finished-at="2023-09-21T11:57:21 IST" duration-ms="733" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- amConfig -->
        <test-method is-config="true" signature="bmConfig()[pri:0, instance:VTiger.CreateContactTest.CreateContactTest@1033576a]" started-at="2023-09-21T11:57:21 IST" name="bmConfig" finished-at="2023-09-21T11:57:22 IST" duration-ms="1209" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bmConfig -->
        <test-method retried="true" signature="verifyUsercreateContactTest()[pri:0, instance:VTiger.CreateContactTest.CreateContactTest@1033576a]" started-at="2023-09-21T11:57:22 IST" name="verifyUsercreateContactTest" finished-at="2023-09-21T11:57:25 IST" duration-ms="2253" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at VTiger.CreateContactTest.CreateContactTest.verifyUsercreateContactTest(CreateContactTest.java:40)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[contact link clicked]]>
            </line>
          </reporter-output>
        </test-method> <!-- verifyUsercreateContactTest -->
        <test-method is-config="true" signature="amConfig()[pri:0, instance:VTiger.CreateContactTest.CreateContactTest@1033576a]" started-at="2023-09-21T11:57:25 IST" name="amConfig" finished-at="2023-09-21T11:57:25 IST" duration-ms="729" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- amConfig -->
        <test-method is-config="true" signature="bmConfig()[pri:0, instance:VTiger.CreateContactTest.CreateContactTest@1033576a]" started-at="2023-09-21T11:57:25 IST" name="bmConfig" finished-at="2023-09-21T11:57:27 IST" duration-ms="1187" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bmConfig -->
        <test-method retried="true" signature="verifyUsercreateContactTest()[pri:0, instance:VTiger.CreateContactTest.CreateContactTest@1033576a]" started-at="2023-09-21T11:57:27 IST" name="verifyUsercreateContactTest" finished-at="2023-09-21T11:57:29 IST" duration-ms="2293" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at VTiger.CreateContactTest.CreateContactTest.verifyUsercreateContactTest(CreateContactTest.java:40)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[contact link clicked]]>
            </line>
          </reporter-output>
        </test-method> <!-- verifyUsercreateContactTest -->
        <test-method is-config="true" signature="amConfig()[pri:0, instance:VTiger.CreateContactTest.CreateContactTest@1033576a]" started-at="2023-09-21T11:57:29 IST" name="amConfig" finished-at="2023-09-21T11:57:30 IST" duration-ms="736" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- amConfig -->
        <test-method is-config="true" signature="bmConfig()[pri:0, instance:VTiger.CreateContactTest.CreateContactTest@1033576a]" started-at="2023-09-21T11:57:30 IST" name="bmConfig" finished-at="2023-09-21T11:57:31 IST" duration-ms="1150" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bmConfig -->
        <test-method signature="verifyUsercreateContactTest()[pri:0, instance:VTiger.CreateContactTest.CreateContactTest@1033576a]" started-at="2023-09-21T11:57:31 IST" name="verifyUsercreateContactTest" finished-at="2023-09-21T11:57:33 IST" duration-ms="2341" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at VTiger.CreateContactTest.CreateContactTest.verifyUsercreateContactTest(CreateContactTest.java:40)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[contact link clicked]]>
            </line>
          </reporter-output>
        </test-method> <!-- verifyUsercreateContactTest -->
        <test-method is-config="true" signature="amConfig()[pri:0, instance:VTiger.CreateContactTest.CreateContactTest@1033576a]" started-at="2023-09-21T11:57:33 IST" name="amConfig" finished-at="2023-09-21T11:57:34 IST" duration-ms="735" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- amConfig -->
        <test-method is-config="true" signature="acConfig()[pri:0, instance:VTiger.CreateContactTest.CreateContactTest@1033576a]" started-at="2023-09-21T11:57:34 IST" name="acConfig" finished-at="2023-09-21T11:57:34 IST" duration-ms="189" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- acConfig -->
        <test-method is-config="true" signature="asConfig()[pri:0, instance:VTiger.CreateContactTest.CreateContactTest@1033576a]" started-at="2023-09-21T11:57:35 IST" name="asConfig" finished-at="2023-09-21T11:57:35 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- asConfig -->
      </class> <!-- VTiger.CreateContactTest.CreateContactTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
